import { LessonNavItem, SubjectLessonCard } from "./types";

export const khtnLessonNavItems: LessonNavItem[] = [
  {
    id: "30",
    label: "Bài 30",
    fullName: "Khái quát về cơ thể người",
    routePath: "/lesson-30",
    fallbackView: "lesson-overview",
    sections: [
      {
        id: "lesson-overview",
        label: "Khái quát cơ thể người",
        iconKey: "book",
      },
      { id: "body-parts", label: "Cấu tạo cơ thể", iconKey: "layers" },
      { id: "coordination", label: "Sự phối hợp cơ thể", iconKey: "activity" },
      { id: "biological-clock", label: "Đồng hồ sinh học", iconKey: "clock" },
      { id: "summary", label: "Tổng kết kiến thức", iconKey: "check" },
      { id: "challenge", label: "Giải trí & Thử thách", iconKey: "game" },
      { id: "characteristics", label: "Đặc điểm riêng", iconKey: "user" },
    ],
  },
  {
    id: "31",
    label: "Bài 31",
    fullName: "Hệ vận động ở người",
    routePath: "/lesson-31",
    fallbackView: "lesson-placeholder",
    sections: [],
  },
  {
    id: "32",
    label: "Bài 32",
    fullName: "Dinh dưỡng và tiêu hóa",
    routePath: "/lesson-32",
    fallbackView: "lesson-32-overview",
    sections: [
      { id: "lesson-32-overview", label: "Tổng quan", iconKey: "book" },
      { id: "lesson-32-explorer", label: "Explorer 3D", iconKey: "layers" },
      { id: "lesson-32-simulation", label: "Simulation", iconKey: "activity" },
      { id: "lesson-32-diseases", label: "Diseases", iconKey: "clock" },
      { id: "lesson-32-nutrition", label: "Nutrition", iconKey: "check" },
      { id: "lesson-32-food-safety", label: "Food Safety", iconKey: "user" },
      { id: "lesson-32-quiz", label: "Quiz", iconKey: "game" },
    ],
  },
  {
    id: "33",
    label: "Bài 33",
    fullName: "Máu và hệ tuần hoàn",
    routePath: "/lesson-33",
    sections: [],
  },
  {
    id: "34",
    label: "Bài 34",
    fullName: "Hệ hô hấp ở người",
    fallbackView: "lesson-placeholder",
    sections: [],
  },
  {
    id: "35",
    label: "Bài 35",
    fullName: "Hệ bài tiết ở người",
    fallbackView: "lesson-placeholder",
    sections: [],
  },
];

export const khtnLessonCards: SubjectLessonCard[] = [
  {
    id: 1,
    title: "Bài 30: Khái quát về cơ thể người",
    description: "Hệ vận động, hệ tuần hoàn, hệ hô hấp, hệ tiêu hóa...",
    image: "https://picsum.photos/seed/bio1/400/300",
    progress: 85,
    duration: "45 phút",
    rating: 4.8,
    routePath: "/lesson-30",
    fallbackView: "lesson-overview",
  },
  {
    id: 2,
    title: "Bài 31: Hệ vận động ở người",
    description: "Cấu tạo xương, cơ, khớp và các bệnh liên quan...",
    image: "https://picsum.photos/seed/bio2/400/300",
    progress: 40,
    duration: "60 phút",
    rating: 4.9,
    routePath: "/lesson-31",
    fallbackView: "lesson-placeholder",
  },
  {
    id: 3,
    title: "Bài 32: Dinh dưỡng và tiêu hóa",
    description: "Các chất dinh dưỡng, cấu tạo hệ tiêu hóa...",
    image: "https://picsum.photos/seed/bio3/400/300",
    progress: 0,
    duration: "50 phút",
    rating: 4.7,
    routePath: "/lesson-32",
    fallbackView: "lesson-32-overview",
  },
  {
    id: 4,
    title: "Bài 33: Máu và hệ tuần hoàn",
    description: "Thành phần máu, cấu tạo tim, mạch máu...",
    image: "https://picsum.photos/seed/bio4/400/300",
    progress: 0,
    duration: "55 phút",
    rating: 4.8,
    routePath: "/lesson-33",
  },
  {
    id: 5,
    title: "Bài 34: Hệ hô hấp ở người",
    description: "Cấu tạo hệ hô hấp, cơ chế trao đổi khí...",
    image: "https://picsum.photos/seed/bio5/400/300",
    progress: 0,
    duration: "40 phút",
    rating: 4.6,
    fallbackView: "lesson-placeholder",
  },
  {
    id: 6,
    title: "Bài 35: Hệ bài tiết ở người",
    description: "Cấu tạo hệ bài tiết, cơ chế tạo nước tiểu...",
    image: "https://picsum.photos/seed/bio6/400/300",
    progress: 0,
    duration: "45 phút",
    rating: 4.7,
    fallbackView: "lesson-placeholder",
  },
];
