import {
  BookText,
  Calculator,
  Languages,
  FlaskConical,
  Globe,
  Users,
  Monitor,
  Wrench,
  Dumbbell,
  Palette,
  Compass,
  MapPin,
} from "lucide-react";

export const SUBJECTS = [
  { id: "ngu-van", name: "Ngữ văn", icon: BookText, color: "#FF6B6B" },
  { id: "toan", name: "Toán", icon: Calculator, color: "#4D96FF" },
  { id: "tieng-anh", name: "Tiếng Anh", icon: Languages, color: "#6BCB77" },
  {
    id: "khtn",
    name: "Khoa học tự nhiên",
    description: "Vật lý, Hóa học, Sinh học",
    icon: FlaskConical,
    color: "#00BFFF",
  },
  {
    id: "ls-dl",
    name: "Lịch sử và Địa lý",
    icon: Globe,
    color: "#FFD93D",
  },
  {
    id: "gdcd",
    name: "Giáo dục công dân",
    icon: Users,
    color: "#6C5CE7",
  },
  { id: "tin-hoc", name: "Tin học", icon: Monitor, color: "#00CEC9" },
  { id: "cong-nghe", name: "Công nghệ", icon: Wrench, color: "#FAB1A0" },
  {
    id: "gdtc",
    name: "Giáo dục thể chất",
    icon: Dumbbell,
    color: "#E17055",
  },
  {
    id: "nghe-thuat",
    name: "Nghệ thuật",
    description: "Âm nhạc, Mĩ thuật",
    icon: Palette,
    color: "#FD79A8",
  },
  {
    id: "trai-nghiem",
    name: "HĐ trải nghiệm, HN",
    icon: Compass,
    color: "#55E6C1",
  },
  {
    id: "dia-phuong",
    name: "GD địa phương",
    icon: MapPin,
    color: "#A29BFE",
  },
];
