import {
  Activity,
  BookOpen,
  ClipboardCheck,
  Gamepad2,
  HeartPulse,
  Layers,
  Leaf,
  PlayCircle,
  Shield,
  ShieldCheck,
  UserCircle2,
} from "lucide-react";
import type {
  LessonNavItem,
  LessonTabConfig,
  SubjectLessonCard,
} from "./lessonTypes";

export const khtnLessonNavItems: LessonNavItem[] = [
  {
    id: "30",
    label: "Bài 30",
    fullName: "Khái quát về cơ thể người",
    routePath: "/lesson-30",
    fallbackView: "lesson-30-overview",
    sections: [
      { id: "lesson-30-overview", label: "Tổng quan", iconKey: "book" },
      { id: "lesson-30-role", label: "Vai trò", iconKey: "activity" },
      { id: "lesson-30-van-dong", label: "Hệ vận động", iconKey: "layers" },
      { id: "lesson-30-tuan-hoan", label: "Hệ tuần hoàn", iconKey: "layers" },
      { id: "lesson-30-ho-hap", label: "Hệ hô hấp", iconKey: "layers" },
      { id: "lesson-30-tieu-hoa", label: "Hệ tiêu hóa", iconKey: "layers" },
      { id: "lesson-30-bai-tiet", label: "Hệ bài tiết", iconKey: "layers" },
      { id: "lesson-30-than-kinh", label: "Hệ thần kinh", iconKey: "layers" },
      { id: "lesson-30-noi-tiet", label: "Hệ nội tiết", iconKey: "layers" },
      { id: "lesson-30-sinh-duc", label: "Hệ sinh dục", iconKey: "layers" },
      { id: "lesson-30-giac-quan", label: "Các giác quan", iconKey: "layers" },
      { id: "lesson-30-summary", label: "Tổng kết", iconKey: "check" },
      { id: "lesson-30-quiz", label: "Quiz )", iconKey: "game" },
    ],
  },
  {
    id: "31",
    label: "Bài 31",
    fullName: "Hệ vận động ở người",
    routePath: "/lesson-31",
    fallbackView: "lesson-placeholder",
    sections: [],
  },
  {
    id: "32",
    label: "Bài 32",
    fullName: "Dinh dưỡng và tiêu hóa",
    routePath: "/lesson-32",
    fallbackView: "lesson-32-overview",
    sections: [
      { id: "lesson-32-overview", label: "Tổng quan", iconKey: "book" },
      { id: "lesson-32-explorer", label: "Khám phá 3D", iconKey: "layers" },
      { id: "lesson-32-simulation", label: "Mô phỏng", iconKey: "activity" },
      { id: "lesson-32-diseases", label: "Bệnh tiêu hóa", iconKey: "clock" },
      { id: "lesson-32-nutrition", label: "Dinh dưỡng", iconKey: "check" },
      { id: "lesson-32-food-safety", label: "An toàn thực phẩm", iconKey: "user" },
      { id: "lesson-32-quiz", label: "Trắc nghiệm", iconKey: "game" },
    ],
  },
  {
    id: "33",
    label: "Bài 33",
    fullName: "Máu và hệ tuần hoàn",
    routePath: "/lesson-33",
    fallbackView: "lesson-33-overview",
    sections: [
      { id: "lesson-33-overview", label: "Tổng quan", iconKey: "book" },
      { id: "lesson-33-explorer", label: "Explorer 3D", iconKey: "layers" },
      { id: "lesson-33-blood", label: "Cấu tạo máu", iconKey: "activity" },
      { id: "lesson-33-simulation", label: "Tuần hoàn", iconKey: "clock" },
      { id: "lesson-33-diseases", label: "Bệnh lý", iconKey: "user" },
      { id: "lesson-33-quiz", label: "Quiz", iconKey: "game" },
    ],
  },
  {
    id: "34",
    label: "Bài 34",
    fullName: "Hệ hô hấp ở người",
    fallbackView: "lesson-placeholder",
    sections: [],
  },
  {
    id: "35",
    label: "Bài 35",
    fullName: "Hệ bài tiết ở người",
    fallbackView: "lesson-placeholder",
    sections: [],
  },
];

export const khtnLessonCards: SubjectLessonCard[] = [
  {
    id: 1,
    title: "Bài 30: Khái quát về cơ thể người",
    description:
      "Tổng quan cơ thể người và vai trò các hệ cơ quan (vận động, tuần hoàn, hô hấp, tiêu hóa, bài tiết, thần kinh, nội tiết, sinh dục, giác quan).",
    image: "https://picsum.photos/seed/human-body/400/300",
    progress: 0,
    duration: "45 phút",
    rating: 4.8,
    routePath: "/lesson-30",
    fallbackView: "lesson-30-overview",
  },
  {
    id: 2,
    title: "Bài 31: Hệ vận động ở người",
    description: "Cấu tạo xương, cơ, khớp và các bệnh liên quan...",
    image: "https://picsum.photos/seed/bio2/400/300",
    progress: 40,
    duration: "60 phút",
    rating: 4.9,
    routePath: "/lesson-31",
    fallbackView: "lesson-placeholder",
  },
  {
    id: 3,
    title: "Bài 32: Dinh dưỡng và tiêu hóa",
    description: "Các chất dinh dưỡng, cấu tạo hệ tiêu hóa...",
    image: "https://picsum.photos/seed/bio3/400/300",
    progress: 0,
    duration: "50 phút",
    rating: 4.7,
    routePath: "/lesson-32",
    fallbackView: "lesson-32-overview",
  },
  {
    id: 4,
    title: "Bài 33: Máu và hệ tuần hoàn",
    description: "Thành phần máu, cấu tạo tim, mạch máu...",
    image: "https://picsum.photos/seed/bio4/400/300",
    progress: 0,
    duration: "55 phút",
    rating: 4.8,
    routePath: "/lesson-33",
    fallbackView: "lesson-33-overview",
  },
  {
    id: 5,
    title: "Bài 34: Hệ hô hấp ở người",
    description: "Cấu tạo hệ hô hấp, cơ chế trao đổi khí...",
    image: "https://picsum.photos/seed/bio5/400/300",
    progress: 0,
    duration: "40 phút",
    rating: 4.6,
    fallbackView: "lesson-placeholder",
  },
  {
    id: 6,
    title: "Bài 35: Hệ bài tiết ở người",
    description: "Cấu tạo hệ bài tiết, cơ chế tạo nước tiểu...",
    image: "https://picsum.photos/seed/bio6/400/300",
    progress: 0,
    duration: "45 phút",
    rating: 4.7,
    fallbackView: "lesson-placeholder",
  },
];

export const lesson30Tabs: LessonTabConfig[] = [
  { label: "Tổng quan", path: "/lesson-30", icon: BookOpen },
  { label: "Vai trò", path: "/lesson-30/vai-tro", icon: Activity },
  { label: "Hệ vận động", path: "/lesson-30/he-van-dong", icon: Layers },
  { label: "Hệ tuần hoàn", path: "/lesson-30/he-tuan-hoan", icon: HeartPulse },
  { label: "Hệ hô hấp", path: "/lesson-30/he-ho-hap", icon: Shield },
  { label: "Hệ tiêu hóa", path: "/lesson-30/he-tieu-hoa", icon: Leaf },
  { label: "Hệ bài tiết", path: "/lesson-30/he-bai-tiet", icon: ShieldCheck },
  { label: "Hệ thần kinh", path: "/lesson-30/he-than-kinh", icon: UserCircle2 },
  { label: "Hệ nội tiết", path: "/lesson-30/he-noi-tiet", icon: Layers },
  { label: "Hệ sinh dục", path: "/lesson-30/he-sinh-duc", icon: UserCircle2 },
  { label: "Giác quan", path: "/lesson-30/giac-quan", icon: Activity },
  { label: "Tổng kết", path: "/lesson-30/tong-ket", icon: ClipboardCheck },
  { label: "Quiz", path: "/lesson-30/quiz", icon: Gamepad2 },
];

export const lesson32Tabs: LessonTabConfig[] = [
  { label: "Tổng quan", path: "/lesson-32", icon: BookOpen },
  { label: "Khám phá 3D", path: "/lesson-32/explorer", icon: Layers },
  { label: "Mô phỏng", path: "/lesson-32/simulation", icon: PlayCircle },
  { label: "Bệnh tiêu hóa", path: "/lesson-32/diseases", icon: ShieldCheck },
  { label: "Dinh dưỡng", path: "/lesson-32/nutrition", icon: Leaf },
  { label: "An toàn thực phẩm", path: "/lesson-32/food-safety", icon: Shield },
  { label: "Kiểm tra", path: "/lesson-32/quiz", icon: ClipboardCheck },
];

export const lesson33Tabs: LessonTabConfig[] = [
  { label: "Tổng quan", path: "/lesson-33", icon: BookOpen },
  { label: "Explorer 3D", path: "/lesson-33/explorer", icon: Layers },
  { label: "Cấu tạo máu", path: "/lesson-33/blood", icon: Activity },
  { label: "Tuần hoàn", path: "/lesson-33/simulation", icon: HeartPulse },
  { label: "Bệnh lý", path: "/lesson-33/diseases", icon: UserCircle2 },
  { label: "Quiz", path: "/lesson-33/quiz", icon: Gamepad2 },
];
