import {
  Activity,
  BookOpen,
  ClipboardCheck,
  Gamepad2,
  HeartPulse,
  Layers,
  Leaf,
  PlayCircle,
  Shield,
  ShieldCheck,
  UserCircle2,
} from "lucide-react";
import type {
  LessonNavItem,
  LessonTabConfig,
  SubjectLessonCard,
} from "./lessonTypes";

export const khtnLessonNavItems: LessonNavItem[] = [
  {
    id: "30",
    label: "Bài 30",
    fullName: "Khái quát về cơ thể người",
    routePath: "/lesson-30",
    fallbackView: "lesson-overview",
    sections: [
      { id: "lesson-overview", label: "Khái quát cơ thể người", iconKey: "book" },
      { id: "body-parts", label: "Cấu tạo cơ thể", iconKey: "layers" },
      { id: "coordination", label: "Sự phối hợp cơ thể", iconKey: "activity" },
      { id: "biological-clock", label: "Đồng hồ sinh học", iconKey: "clock" },
      { id: "summary", label: "Tổng kết kiến thức", iconKey: "check" },
      { id: "challenge", label: "Giải trí & Thử thách", iconKey: "game" },
      { id: "characteristics", label: "Đặc điểm riêng", iconKey: "user" },
    ],
  },
  {
    id: "31",
    label: "Bài 31",
    fullName: "Hệ vận động ở người",
    routePath: "/lesson-31",
    fallbackView: "lesson-placeholder",
    sections: [],
  },
  {
    id: "32",
    label: "Bài 32",
    fullName: "Dinh dưỡng và tiêu hóa",
    routePath: "/lesson-32",
    fallbackView: "lesson-32-overview",
    sections: [
      { id: "lesson-32-overview", label: "Tổng quan", iconKey: "book" },
      { id: "lesson-32-explorer", label: "Khám phá 3D", iconKey: "layers" },
      { id: "lesson-32-simulation", label: "Mô phỏng", iconKey: "activity" },
      { id: "lesson-32-diseases", label: "Bệnh tiêu hóa", iconKey: "clock" },
      { id: "lesson-32-nutrition", label: "Dinh dưỡng", iconKey: "check" },
      { id: "lesson-32-food-safety", label: "An toàn thực phẩm", iconKey: "user" },
      { id: "lesson-32-quiz", label: "Trắc nghiệm", iconKey: "game" },
    ],
  },
  {
    id: "33",
    label: "Bài 33",
    fullName: "Máu và hệ tuần hoàn",
    routePath: "/lesson-33",
    fallbackView: "lesson-33-overview",
    sections: [
      { id: "lesson-33-overview", label: "Tổng quan", iconKey: "book" },
      { id: "lesson-33-explorer", label: "Explorer 3D", iconKey: "layers" },
      { id: "lesson-33-blood", label: "Cấu tạo máu", iconKey: "activity" },
      { id: "lesson-33-simulation", label: "Tuần hoàn", iconKey: "clock" },
      { id: "lesson-33-diseases", label: "Bệnh lý", iconKey: "user" },
      { id: "lesson-33-quiz", label: "Quiz", iconKey: "game" },
    ],
  },
  {
    id: "34",
    label: "Bài 34",
    fullName: "Hệ hô hấp ở người",
    fallbackView: "lesson-placeholder",
    sections: [],
  },
  {
    id: "35",
    label: "Bài 35",
    fullName: "Hệ bài tiết ở người",
    fallbackView: "lesson-placeholder",
    sections: [],
  },
];

export const khtnLessonCards: SubjectLessonCard[] = [
  {
    id: 1,
    title: "Bài 30: Khái quát về cơ thể người",
    description: "Hệ vận động, hệ tuần hoàn, hệ hô hấp, hệ tiêu hóa...",
    image: "https://picsum.photos/seed/bio1/400/300",
    progress: 85,
    duration: "45 phút",
    rating: 4.8,
    routePath: "/lesson-30",
    fallbackView: "lesson-overview",
  },
  {
    id: 2,
    title: "Bài 31: Hệ vận động ở người",
    description: "Cấu tạo xương, cơ, khớp và các bệnh liên quan...",
    image: "https://picsum.photos/seed/bio2/400/300",
    progress: 40,
    duration: "60 phút",
    rating: 4.9,
    routePath: "/lesson-31",
    fallbackView: "lesson-placeholder",
  },
  {
    id: 3,
    title: "Bài 32: Dinh dưỡng và tiêu hóa",
    description: "Các chất dinh dưỡng, cấu tạo hệ tiêu hóa...",
    image: "https://picsum.photos/seed/bio3/400/300",
    progress: 0,
    duration: "50 phút",
    rating: 4.7,
    routePath: "/lesson-32",
    fallbackView: "lesson-32-overview",
  },
  {
    id: 4,
    title: "Bài 33: Máu và hệ tuần hoàn",
    description: "Thành phần máu, cấu tạo tim, mạch máu...",
    image: "https://picsum.photos/seed/bio4/400/300",
    progress: 0,
    duration: "55 phút",
    rating: 4.8,
    routePath: "/lesson-33",
    fallbackView: "lesson-33-overview",
  },
  {
    id: 5,
    title: "Bài 34: Hệ hô hấp ở người",
    description: "Cấu tạo hệ hô hấp, cơ chế trao đổi khí...",
    image: "https://picsum.photos/seed/bio5/400/300",
    progress: 0,
    duration: "40 phút",
    rating: 4.6,
    fallbackView: "lesson-placeholder",
  },
  {
    id: 6,
    title: "Bài 35: Hệ bài tiết ở người",
    description: "Cấu tạo hệ bài tiết, cơ chế tạo nước tiểu...",
    image: "https://picsum.photos/seed/bio6/400/300",
    progress: 0,
    duration: "45 phút",
    rating: 4.7,
    fallbackView: "lesson-placeholder",
  },
];

export const lesson30Tabs: LessonTabConfig[] = [
  { label: "Tổng quan", path: "/lesson-30" },
  { label: "Cấu tạo cơ thể", path: "/lesson-30/body-parts" },
  { label: "Sự phối hợp", path: "/lesson-30/coordination" },
  { label: "Đồng hồ sinh học", path: "/lesson-30/biological-clock" },
  { label: "Đặc điểm riêng", path: "/lesson-30/characteristics" },
  { label: "Thử thách", path: "/lesson-30/challenge" },
  { label: "Tổng kết", path: "/lesson-30/summary" },
];

export const lesson32Tabs: LessonTabConfig[] = [
  { label: "Tổng quan", path: "/lesson-32", icon: BookOpen },
  { label: "Khám phá 3D", path: "/lesson-32/explorer", icon: Layers },
  { label: "Mô phỏng", path: "/lesson-32/simulation", icon: PlayCircle },
  { label: "Bệnh tiêu hóa", path: "/lesson-32/diseases", icon: ShieldCheck },
  { label: "Dinh dưỡng", path: "/lesson-32/nutrition", icon: Leaf },
  { label: "An toàn thực phẩm", path: "/lesson-32/food-safety", icon: Shield },
  { label: "Kiểm tra", path: "/lesson-32/quiz", icon: ClipboardCheck },
];

export const lesson33Tabs: LessonTabConfig[] = [
  { label: "Tổng quan", path: "/lesson-33", icon: BookOpen },
  { label: "Explorer 3D", path: "/lesson-33/explorer", icon: Layers },
  { label: "Cấu tạo máu", path: "/lesson-33/blood", icon: Activity },
  { label: "Tuần hoàn", path: "/lesson-33/simulation", icon: HeartPulse },
  { label: "Bệnh lý", path: "/lesson-33/diseases", icon: UserCircle2 },
  { label: "Quiz", path: "/lesson-33/quiz", icon: Gamepad2 },
];
